// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdpxnhtaexnbbnrrnpuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcHhuaHRhZXhuYmJucnJucHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjIzNzAsImV4cCI6MjA1OTczODM3MH0.x5aHBAc27QI3a2aswXO0IvoYc03KkDSMd1u3z4UFYbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);